version: '3'
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1

  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ParsingDB




    